package Main_Windows;



import javax.swing.JFrame;
import javax.swing.JOptionPane;
import Drug_Addiction.DA_Window1;
import Internet_Addiction.IA_Window1;
import Anxiety.Anxiety_Window1;
import Depression.Depression_Window1;
import Sexual_Addiction.SA_Window1;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Wellington Mpofu
 */
public class Main_Menu extends javax.swing.JFrame {

    /**
     * Creates new form Main2JFrame
     */
    public Main_Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton_Depression = new javax.swing.JButton();
        jButton_Anxiety = new javax.swing.JButton();
        jButton_Cyber = new javax.swing.JButton();
        jButton_Addiction = new javax.swing.JButton();
        jButton_Addiction1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setPreferredSize(new java.awt.Dimension(1366, 710));
        jPanel1.setLayout(null);

        jButton_Depression.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_Depression.setText("DEPRESSION TEST");
        jButton_Depression.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DepressionActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Depression);
        jButton_Depression.setBounds(900, 180, 249, 40);

        jButton_Anxiety.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_Anxiety.setText("ANXIETY TEST");
        jButton_Anxiety.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AnxietyActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Anxiety);
        jButton_Anxiety.setBounds(900, 270, 249, 40);

        jButton_Cyber.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_Cyber.setText("INTERNET ADDICTION TEST");
        jButton_Cyber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CyberActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Cyber);
        jButton_Cyber.setBounds(900, 360, 249, 40);

        jButton_Addiction.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_Addiction.setText("DRUG ADDICTION TEST");
        jButton_Addiction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AddictionActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Addiction);
        jButton_Addiction.setBounds(900, 450, 249, 40);

        jButton_Addiction1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_Addiction1.setText("SEXUAL ADDICTION TEST");
        jButton_Addiction1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Addiction1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Addiction1);
        jButton_Addiction1.setBounds(900, 540, 249, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Wellington\\Documents\\INFORMATICS\\Part 2.1\\Human Computer Interaction [SCI 2102]\\Research\\Psychology App\\Main Menu.jpg")); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 1366, 710);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12300, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        //setSize(1366,768);
//        this.jLabel1.setText("Welcome to Students Mind Care where we believe mental illness is not a choice but recovery is." +"\n" + "With that in mind "
//                + "the mental health tests below aim to serve as the start of your journey to recovery by helping you better understand what you "
//                + "may be going through. These tests are not meant to replace professional help and we encourage you to make an effort to visit"
//                + " your school counsellor or any mental health professional as they will be in a better position to diagnose and help you with "
//                + "what you may be going through probably better than we can. And most importantly remember recovery is an evolution not a miracle."
//                + " Stay patient.");
    }//GEN-LAST:event_formWindowActivated

    private void jButton_DepressionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DepressionActionPerformed
        Depression_Window1 dw = new Depression_Window1();
        dw.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton_DepressionActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        int result = JOptionPane.showConfirmDialog(rootPane, "Do you want to exit?", "Exit confirmation", JOptionPane.YES_NO_OPTION);
        if(result == JOptionPane.YES_OPTION){
            setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            
        }
        else if(result == JOptionPane.NO_OPTION){
            setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        }
    }//GEN-LAST:event_formWindowClosing

    private void jButton_AnxietyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AnxietyActionPerformed
        Anxiety_Window1 dw = new Anxiety_Window1();
        dw.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton_AnxietyActionPerformed

    private void jButton_CyberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CyberActionPerformed
        IA_Window1 dw = new IA_Window1();
        dw.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton_CyberActionPerformed

    private void jButton_AddictionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AddictionActionPerformed
        DA_Window1 dw = new DA_Window1();
        dw.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton_AddictionActionPerformed

    private void jButton_Addiction1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Addiction1ActionPerformed
        SA_Window1 dw = new SA_Window1();
        dw.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton_Addiction1ActionPerformed

    /**
     * @param args the command line arguments+
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Addiction;
    private javax.swing.JButton jButton_Addiction1;
    private javax.swing.JButton jButton_Anxiety;
    private javax.swing.JButton jButton_Cyber;
    private javax.swing.JButton jButton_Depression;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
